export { default as Posts } from './Posts.jsx';
export { default as Home } from './Home.jsx';
export { default as PostDetail } from './PostDetail.jsx';
export { default as CreatePost } from './CreatePost/CreatePost.jsx';
export { default as Profile } from './Profile.jsx';
export { default as Registration } from './Registration.jsx';
export { default as Videos } from './Videos.jsx';
export { default as FourOFour } from './FourOFour.jsx';
export { default as Contacts } from './Contacts.jsx';